spring:
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    password: qwe123qwe123!
    url: jdbc:log4jdbc:mysql://localhost:3306/tech_board?allowPublicKeyRetrieval=true&useSSL=false
    username: root
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
